# Generated by Django 4.2.12 on 2024-11-27 20:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(choices=[('Pediatric_wheelchair', 'Pediatric wheelchair'), ('American_wheelchair', 'American wheelchair'), ('FWP_wheelchair', 'FWP wheelchair'), ('Walker', 'Walker'), ('Crutch', 'Crutch'), ('Cane', 'Cane')], max_length=100)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'XL')], max_length=50, null=True)),
                ('cause_of_need', models.CharField(blank=True, choices=[('Cerebral_Palsy', 'Cerebral Palsy'), ('Muscular_Dystrophy', 'Muscular Dystrophy'), ('Stroke', 'Stroke'), ('Epilepsy', 'Epilepsy'), ('Multiple_Sclerosis', 'Multiple Sclerosis'), ('Multiple_Disabilities', 'Multiple Disabilities'), ('Spina_Bifida', 'Spina Bifida'), ('Burn_Injury', 'Burn Injury'), ('Downs_Syndrome', "Down's Syndrome"), ('Spinal_Injury', 'Spinal Injury'), ('Brain_and_Head_Injuries', 'Brain and Head Injuries'), ('Amputee', 'Amputee'), ('Polio', 'Polio'), ('Arthritis', 'Arthritis')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='disabilityrecord',
            old_name='seat_depth',
            new_name='hip_width',
        ),
        migrations.RenameField(
            model_name='disabilityrecord',
            old_name='seat_width',
            new_name='thigh_length',
        ),
        migrations.RemoveField(
            model_name='disabilityrecord',
            name='wheelchair_type',
        ),
        migrations.AddField(
            model_name='disabilityrecord',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipment'),
        ),
    ]
