# Generated by Django 4.2.12 on 2024-11-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilityrecord',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('Pediatric_wheelchair', 'Pediatric wheelchair'), ('American_wheelchair', 'American wheelchair'), ('FWP_wheelchair', 'FWP wheelchair'), ('Walker', 'Walker'), ('Crutch', 'Crutch'), ('Cane', 'Cane')], max_length=100, null=True),
        ),
    ]
