# Generated by Django 5.1.3 on 2024-11-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_disabilityrecord_gender_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilityrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
