# Generated by Django 4.2.12 on 2024-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipment_cause_of_need_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disabilityrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='disabilityrecord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warrant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
