# Generated by Django 4.2.12 on 2024-11-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_disabilityrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilityrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
