# Generated by Django 4.2.12 on 2024-12-03 18:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_disabilityrecord_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', 'first_name']},
        ),
        migrations.AlterField(
            model_name='disabilityrecord',
            name='kebele_id_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='disabilityrecord',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_image/avatar.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_image/avatar.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='warrant',
            name='id_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
