# Generated by Django 4.2.12 on 2024-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_disabilityrecord_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warrant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
