# Generated by Django 5.1.3 on 2024-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilityrecord',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
