# Generated by Django 5.1.3 on 2024-11-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disabilityrecord_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
